### ISSUE TITLE
One my ecos are randomly not disconnected after changing temperature. Leaves red ring lit and makes the device unusable until I reinsert the batteries.

### ISSUE THREAD

**Issue by ariselseng** [AdamStrojek/libetrv#36]
Anyone having this issue? Happens about once a day.
I have tried several different battery brands as well.

**Comment by ariselseng** [comment]
> yes, i get them so often that i gave up on this library.

A workaround is to use rfkill to block bluetooth and unblock it again after running libetrv cli. Then the red ring stops.

**Comment by jeanbaptistelab** [comment]
I'm also having this issue, which is very annoying... I've looked into it and I think I found what the underlying cause is: the BLE connections are not closed, they are just hanging idly.
When this happens, I SSH to my HomeAssistant OS and check that there are indeed (one or more) stray connections
```
[core-ssh ~]$ bluetoothctl devices | cut -f2 -d' ' | while read uuid; do bluetoothctl info $uuid; done|grep -e "Device\|Connected\|Name"

Device 00:04:2F:B2:XX:XX (public)
        Name: 2;0:04:2F:B2:XX:XX;eTRV
        Connected: yes
```
I can get the valve to disconnect by using `bluetoothctl power off`, the connections are effectively closed after this command (can take a few seconds).

I believe the origin of this problem lies in the interactions between this library and `bluepy`, I have some experience with `bluepy`and am currently investigating this, but I'm right now learning about the whole "Home Assistant add-on" eco-system so I need a bit of time to get going, but I'll definitely update this thread with my findings...

**Comment by jeanbaptistelab** [comment]
@HBDK I believe you are the author of the HomeAssistant Add-on Eco2-Tools, is that correct ? If so, could you share your Dockerfile for [etrv2mqtt](https://github.com/HBDK/Eco2-Tools/tree/master/etrv2mqtt) ? That way, I can rebuild it with some debug/attempts and see if I can fix the issue. That would save me some time figuring out how this image is built/works by myself...

**Comment by AdamStrojek** [comment]
> I'm also having this issue, which is very annoying... I've looked into it and I think I found what the underlying cause is: the BLE connections are not closed, they are just hanging idly. When this happens, I SSH to my HomeAssistant OS and check that there are indeed (one or more) stray connections

Unfortunately there is no good way how to solve this issue on library level. BLE subsystem in Linux is very picky if something goes wrong. Only reliable way how to handle disconnect in linux is to reset . Also like you mentioned bluepy is not the most reliable library.

If you want to debug it on library leve, you can use `cli.py` file included in library, but it was only tested on Raspberry Pi device. This should allow you to attach debugger and test it on any level
https://github.com/AdamStrojek/libetrv/blob/28a48676f15180d71feadca163859d4b2d8832c3/libetrv/cli.py

**Comment by HBDK** [comment]
@jeanbaptistelab the docker files are in this repo:

https://github.com/HBDK/Eco2-tools-docker

Ping me once a fix is in master on etrv2mqtt and I’ll update the add on.
